### ISSUE TITLE
clarifications re: integration_test resource cleanup

### ISSUE THREAD

**Issue by riwsky** [energyhub/secretly#1]
https://github.com/energyhub/secretly/blob/73475d64f6971ab844ff12f053e82bd5e8aeed04/integration_test.go#L20

happens later down below

**Comment by riwsky** [comment]
ahhh legit, legit—can you clarify that in a comment there or near the second remove?

**Comment by riwsky** [comment]
unrelated: you use reflect.DeepEqual in main_test, might as well use it in integration_test too, yeah? or is there another thing I'm missing?

**Comment by riwsky** [comment]
also: apologies for using issues, this just seemed less bad than trying to tie it to a random commit or doing it via something that wouldn't give code-link context

**Comment by jwilner** [comment]
@riwsky there is a comment on the second remove. I think this is adequately commented. 

I'll add a comment about the equals method. Short of it is that deepEquals seemed to be comparing the underlying `cap`.

**Comment by jwilner** [comment]
Rather, it's that nil empty slice and a non-nil empty slice don't return equal.

**Comment by jwilner** [comment]
https://golang.org/pkg/reflect/#DeepEqual
